apiVersion: v1
kind: Service
metadata:
  name: locust-exporter
  namespace: locust
  labels:
    app: locust-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9646"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: locust-exporter
  ports:
    - name: metrics
      port: 9646
      targetPort: 9646
