# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: argussdkapi.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'argussdkapi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61rgussdkapi.proto\x12\neasemob.pb\"\xd4\x03\n\x0b\x41rgusSdkApi\x12\x0b\n\x03lts\x18\x01 \x02(\x03\x12\x0b\n\x03vid\x18\x02 \x02(\x03\x12\x0b\n\x03uid\x18\x03 \x02(\t\x12\x14\n\x0csdkServiceId\x18\x04 \x02(\t\x12\x13\n\x0boperationId\x18\x05 \x02(\t\x12\x15\n\roperationName\x18\x06 \x02(\t\x12\x15\n\roperationType\x18\x07 \x02(\t\x12\x11\n\trequestid\x18\x08 \x02(\t\x12\x14\n\x0csubrequestid\x18\t \x02(\t\x12\x0b\n\x03net\x18\n \x02(\x05\x12\x15\n\rrequestMethod\x18\x0b \x02(\t\x12\x12\n\nrequestUrl\x18\x0c \x02(\t\x12\x13\n\x0brequestName\x18\r \x02(\t\x12\x15\n\rrequestElapse\x18\x0e \x02(\x03\x12\r\n\x05msgId\x18\x0f \x02(\t\x12\x15\n\raccessChannel\x18\x10 \x02(\t\x12\x11\n\tisSuccess\x18\x11 \x02(\x05\x12\x12\n\nsdkProduct\x18\x12 \x02(\x05\x12\x11\n\tisLastApi\x18\x13 \x02(\x05\x12\x0c\n\x04\x63ode\x18\x14 \x02(\x05\x12\x10\n\x08\x63odeDesc\x18\x15 \x02(\t\x12\x0e\n\x06\x61ppkey\x18\x16 \x02(\t\x12\x13\n\x0bresultCount\x18\x17 \x02(\x05\x12\x13\n\x0bmessageType\x18\x18 \x02(\x05\x42\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'argussdkapi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_ARGUSSDKAPI']._serialized_start=34
  _globals['_ARGUSSDKAPI']._serialized_end=502
# @@protoc_insertion_point(module_scope)
