# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: argussdkinit.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'argussdkinit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61rgussdkinit.proto\x12\neasemob.pb\"\xd9\x01\n\x0c\x41rgusSdkInit\x12\x0b\n\x03lts\x18\x01 \x02(\x03\x12\x0b\n\x03vid\x18\x02 \x02(\x03\x12\x0e\n\x06\x61ppkey\x18\x03 \x02(\t\x12\x14\n\x0csdkServiceId\x18\x04 \x02(\t\x12\n\n\x02os\x18\x05 \x02(\x05\x12\x12\n\nsdkVersion\x18\x06 \x02(\t\x12\x12\n\nsdkProduct\x18\x07 \x02(\x05\x12\x10\n\x08\x64\x65viceId\x18\x08 \x02(\t\x12\x0b\n\x03\x64id\x18\t \x02(\t\x12\x0b\n\x03net\x18\n \x02(\x05\x12\x14\n\x0cuikitVersion\x18\x0b \x02(\t\x12\x13\n\x0bsdkPlatform\x18\x0c \x02(\x05\x42\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'argussdkinit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_ARGUSSDKINIT']._serialized_start=35
  _globals['_ARGUSSDKINIT']._serialized_end=252
# @@protoc_insertion_point(module_scope)
