# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arguscrashevent.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'arguscrashevent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61rguscrashevent.proto\x12\neasemob.pb\"\xa4\x03\n\x0e\x43hatCrashEvent\x12\x0b\n\x03lts\x18\x01 \x02(\x03\x12\x0b\n\x03vid\x18\x02 \x02(\x03\x12\x14\n\x0csdkServiceId\x18\x03 \x02(\t\x12\x0b\n\x03uid\x18\x04 \x02(\t\x12\x0e\n\x06\x65lapse\x18\x05 \x02(\x03\x12\x10\n\x08\x63rashVer\x18\x06 \x02(\x05\x12\x0f\n\x07\x64mpType\x18\x07 \x02(\x05\x12\x0e\n\x06lstLts\x18\x08 \x02(\x03\x12\x14\n\x0clstCrashAddr\x18\t \x02(\x03\x12\x12\n\nlstLdBegin\x18\n \x02(\x03\x12\x10\n\x08lstLdEnd\x18\x0b \x02(\x03\x12\x11\n\tlstSdkVer\x18\x0c \x02(\t\x12\x12\n\nlstNetwork\x18\r \x02(\x05\x12\x13\n\x0blstCrashUid\x18\x0e \x02(\t\x12\x12\n\nisDumpFile\x18\x0f \x02(\x05\x12\n\n\x02os\x18\x10 \x02(\x05\x12\x10\n\x08\x64\x65viceid\x18\x11 \x02(\t\x12\x0e\n\x06\x61ppkey\x18\x12 \x02(\t\x12\x12\n\nmoduleName\x18\x13 \x02(\t\x12\x15\n\rmoduleBuildNo\x18\x14 \x02(\x03\x12\x0b\n\x03\x64id\x18\x15 \x02(\t\x12\x0f\n\x07\x63puarch\x18\x16 \x02(\x05\x12\x0f\n\x07\x61\x63\x63ount\x18\x17 \x02(\tB\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arguscrashevent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_CHATCRASHEVENT']._serialized_start=38
  _globals['_CHATCRASHEVENT']._serialized_end=458
# @@protoc_insertion_point(module_scope)
