# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: conferencebody.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'conferencebody.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63onferencebody.proto\x12\neasemob.pb\"\xc8\x07\n\x0e\x43onferenceBody\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x37\n\toperation\x18\x02 \x01(\x0e\x32$.easemob.pb.ConferenceBody.Operation\x12\x15\n\rconference_id\x18\x03 \x01(\t\x12-\n\x04type\x18\x04 \x01(\x0e\x32\x1f.easemob.pb.ConferenceBody.Type\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x0f\n\x07network\x18\x06 \x01(\t\x12\x0f\n\x07version\x18\x07 \x01(\t\x12\x35\n\x08identity\x18\x08 \x01(\x0e\x32#.easemob.pb.ConferenceBody.Identity\x12\x10\n\x08\x64uration\x18\t \x01(\t\x12\x11\n\tpeer_name\x18\n \x01(\t\x12\x38\n\nend_reason\x18\x0b \x01(\x0e\x32$.easemob.pb.ConferenceBody.EndReason\x12\x31\n\x06status\x18\x0c \x01(\x0b\x32!.easemob.pb.ConferenceBody.Status\x12\x11\n\tis_direct\x18\r \x01(\x08\x12\x42\n\x0c\x63ontrol_type\x18\x0e \x01(\x0e\x32,.easemob.pb.ConferenceBody.StreamControlType\x12\x12\n\nroute_flag\x18\x0f \x01(\x05\x12\x11\n\troute_key\x18\x10 \x01(\t\x1a\x1c\n\x06Status\x12\x12\n\nerror_code\x18\x01 \x01(\x05\"\x86\x01\n\tOperation\x12\x08\n\x04JOIN\x10\x00\x12\x0c\n\x08INITIATE\x10\x01\x12\x13\n\x0f\x41\x43\x43\x45PT_INITIATE\x10\x02\x12\n\n\x06\x41NSWER\x10\x03\x12\r\n\tTERMINATE\x10\x04\x12\n\n\x06REMOVE\x10\x05\x12\x12\n\x0eSTREAM_CONTROL\x10\x06\x12\x11\n\rMEDIA_REQUEST\x10\x07\"\x1c\n\x04Type\x12\t\n\x05VOICE\x10\x00\x12\t\n\x05VIDEO\x10\x01\"\"\n\x08Identity\x12\n\n\x06\x43\x41LLER\x10\x00\x12\n\n\x06\x43\x41LLEE\x10\x01\"e\n\tEndReason\x12\n\n\x06HANGUP\x10\x00\x12\x0e\n\nNORESPONSE\x10\x01\x12\n\n\x06REJECT\x10\x02\x12\x08\n\x04\x42USY\x10\x03\x12\x08\n\x04\x46\x41IL\x10\x04\x12\x0f\n\x0bUNSUPPORTED\x10\x05\x12\x0b\n\x07OFFLINE\x10\x06\"Y\n\x11StreamControlType\x12\x0f\n\x0bPAUSE_VOICE\x10\x00\x12\x10\n\x0cRESUME_VOICE\x10\x01\x12\x0f\n\x0bPAUSE_VIDEO\x10\x02\x12\x10\n\x0cRESUME_VIDEO\x10\x03\x42\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conferencebody_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_CONFERENCEBODY']._serialized_start=37
  _globals['_CONFERENCEBODY']._serialized_end=1005
  _globals['_CONFERENCEBODY_STATUS']._serialized_start=580
  _globals['_CONFERENCEBODY_STATUS']._serialized_end=608
  _globals['_CONFERENCEBODY_OPERATION']._serialized_start=611
  _globals['_CONFERENCEBODY_OPERATION']._serialized_end=745
  _globals['_CONFERENCEBODY_TYPE']._serialized_start=747
  _globals['_CONFERENCEBODY_TYPE']._serialized_end=775
  _globals['_CONFERENCEBODY_IDENTITY']._serialized_start=777
  _globals['_CONFERENCEBODY_IDENTITY']._serialized_end=811
  _globals['_CONFERENCEBODY_ENDREASON']._serialized_start=813
  _globals['_CONFERENCEBODY_ENDREASON']._serialized_end=914
  _globals['_CONFERENCEBODY_STREAMCONTROLTYPE']._serialized_start=916
  _globals['_CONFERENCEBODY_STREAMCONTROLTYPE']._serialized_end=1005
# @@protoc_insertion_point(module_scope)
