# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rosterbody.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'rosterbody.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import jid_pb2 as jid__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10rosterbody.proto\x12\neasemob.pb\x1a\tjid.proto\"\xbb\x04\n\nRosterBody\x12\x33\n\toperation\x18\x01 \x01(\x0e\x32 .easemob.pb.RosterBody.Operation\x12-\n\x06status\x18\x02 \x01(\x0b\x32\x1d.easemob.pb.RosterBody.Status\x12\x1d\n\x04\x66rom\x18\x03 \x01(\x0b\x32\x0f.easemob.pb.JID\x12\x1b\n\x02to\x18\x04 \x03(\x0b\x32\x0f.easemob.pb.JID\x12\x0e\n\x06reason\x18\x05 \x01(\t\x12\x12\n\nroster_ver\x18\x06 \x01(\t\x12\x14\n\x0c\x62i_direction\x18\x07 \x01(\x08\x1a\xb8\x01\n\x06Status\x12;\n\nerror_code\x18\x01 \x01(\x0e\x32\'.easemob.pb.RosterBody.Status.ErrorCode\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\\\n\tErrorCode\x12\x06\n\x02OK\x10\x00\x12\x12\n\x0eUSER_NOT_EXIST\x10\x01\x12\x17\n\x13USER_ALREADY_FRIEND\x10\x02\x12\x1a\n\x16USER_ALREADY_BLACKLIST\x10\x03\"\x97\x01\n\tOperation\x12\x0e\n\nGET_ROSTER\x10\x00\x12\x11\n\rGET_BLACKLIST\x10\x01\x12\x07\n\x03\x41\x44\x44\x10\x02\x12\n\n\x06REMOVE\x10\x03\x12\n\n\x06\x41\x43\x43\x45PT\x10\x04\x12\x0b\n\x07\x44\x45\x43LINE\x10\x05\x12\x07\n\x03\x42\x41N\x10\x06\x12\t\n\x05\x41LLOW\x10\x07\x12\x11\n\rREMOTE_ACCEPT\x10\x08\x12\x12\n\x0eREMOTE_DECLINE\x10\tB\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rosterbody_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_ROSTERBODY']._serialized_start=44
  _globals['_ROSTERBODY']._serialized_end=615
  _globals['_ROSTERBODY_STATUS']._serialized_start=277
  _globals['_ROSTERBODY_STATUS']._serialized_end=461
  _globals['_ROSTERBODY_STATUS_ERRORCODE']._serialized_start=369
  _globals['_ROSTERBODY_STATUS_ERRORCODE']._serialized_end=461
  _globals['_ROSTERBODY_OPERATION']._serialized_start=464
  _globals['_ROSTERBODY_OPERATION']._serialized_end=615
# @@protoc_insertion_point(module_scope)
