# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: statisticsbody.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'statisticsbody.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14statisticsbody.proto\x12\neasemob.pb\"\xbc\x05\n\x0eStatisticsBody\x12\x37\n\toperation\x18\x01 \x01(\x0e\x32$.easemob.pb.StatisticsBody.Operation\x12-\n\x02os\x18\x02 \x01(\x0e\x32!.easemob.pb.StatisticsBody.OsType\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x37\n\x07network\x18\x04 \x01(\x0e\x32&.easemob.pb.StatisticsBody.NetworkType\x12\x0f\n\x07im_time\x18\x05 \x01(\r\x12\x11\n\tchat_time\x18\x06 \x01(\r\x12\x10\n\x08location\x18\x07 \x01(\t\x12\x1b\n\x13replace_device_name\x18\x08 \x01(\t\x12\x12\n\nsession_id\x18\t \x01(\t\x12\x0e\n\x06reason\x18\n \x01(\t\"\x92\x01\n\tOperation\x12\x0f\n\x0bINFORMATION\x10\x00\x12\x10\n\x0cUSER_REMOVED\x10\x01\x12\x1d\n\x19USER_LOGIN_ANOTHER_DEVICE\x10\x02\x12\"\n\x1eUSER_KICKED_BY_CHANGE_PASSWORD\x10\x03\x12\x1f\n\x1bUSER_KICKED_BY_OTHER_DEVICE\x10\x04\"w\n\x06OsType\x12\n\n\x06OS_IOS\x10\x00\x12\x0e\n\nOS_ANDROID\x10\x01\x12\x0c\n\x08OS_LINUX\x10\x02\x12\n\n\x06OS_OSX\x10\x03\x12\n\n\x06OS_WIN\x10\x04\x12\r\n\tOS_CUSTOM\x10\x05\x12\x0e\n\nOS_HARMONY\x10\x06\x12\x0c\n\x08OS_OTHER\x10\x10\"s\n\x0bNetworkType\x12\x10\n\x0cNETWORK_NONE\x10\x00\x12\x10\n\x0cNETWORK_WIFI\x10\x01\x12\x0e\n\nNETWORK_4G\x10\x02\x12\x0e\n\nNETWORK_3G\x10\x03\x12\x0e\n\nNETWORK_2G\x10\x04\x12\x10\n\x0cNETWORK_WIRE\x10\x05\x42\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statisticsbody_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_STATISTICSBODY']._serialized_start=37
  _globals['_STATISTICSBODY']._serialized_end=737
  _globals['_STATISTICSBODY_OPERATION']._serialized_start=353
  _globals['_STATISTICSBODY_OPERATION']._serialized_end=499
  _globals['_STATISTICSBODY_OSTYPE']._serialized_start=501
  _globals['_STATISTICSBODY_OSTYPE']._serialized_end=620
  _globals['_STATISTICSBODY_NETWORKTYPE']._serialized_start=622
  _globals['_STATISTICSBODY_NETWORKTYPE']._serialized_end=737
# @@protoc_insertion_point(module_scope)
